---
url: uskb.github.io
exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Unstructured and Structured KBs @ AKBC 2020"
keywords:    "workshop, knowledge"
description: "The official website for the Workshop on Unstructured and Structured KBs @ AKBC 2020"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
